amcl:
  ros__parameters:
    use_sim_time: False
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    scan_topic: "scan"
    map_topic: "map"
    transform_tolerance: 0.5
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1.0
    particles: 300
    pf_err: 0.05
    pf_z: 0.99

map_server:
  ros__parameters:
    yaml_filename: "/path/to/your/map.yaml"
    use_sim_time: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False

controller_server:
  ros__parameters:
    expected_controller_frequency: 20.0
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    use_sim_time: False