slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_file_name: ""
    map_start_pose: [0.0, 0.0, 0.0]
    minimum_time_interval: 1.0
    scan_topic: /scan
    frequency: 10.0 
    resolution: 0.05
    max_laser_range: 30.0
    minimum_travel_distance: 0.2
    transform_publish_period: 0.05
    scan_subscriber_queue_size: 20 
    map_update_interval: 2.0
    use_scan_matching: true
    laser_scan_topic: /scan
    mode: mapping
    optimization_frequency: 1.0
    max_keyframes_in_map: 1000
    max_lidar_range: 30.0
    loop_closure_enabled: true
    loop_closure_threshold: 210
    loop_closure_search_radius: 8.0
    queue_size: 100